services:
  frontend:
    image: loe-music-client-angular
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      ENV: production
      TZ: America/Chicago
      API_ENDPOINT: 'https://loe-service.outlawdesigns.io'
      LOE_DOMAIN: 'https://loe.outlawdesigns.io/'
      AUTH_CLIENT_ID: 'loesuite-music-webapp'
      AUTH_DISCOVERY_URI: 'https://auth.outlawdesigns.io/.well-known/openid-configuration'
      AUTH_REDIRECT_URL: 'http://localhost:3000/token/'
      AUTH_LOGOUT_URL: 'http://localhost:3000/logout/'
      AUTH_SCOPE: 'offline_access offline openid'
    ports:
      - '3000:8080'
